### ISSUE TITLE
Conflicting types for 'i2d_CVC_CERT' on MacOS

### ISSUE THREAD

**Issue by Y2JChamp** [frankmorgner/openpace#53]
### Expected behaviour

When running make no errors should be filed.

### Actual behaviour

When running "make" on MacOS, i get the following error:
 conflicting types for 'i2d_CVC_CERT'

### Steps to reproduce

1. ./configure
2. make

### Logs

```
cv_cert.c:243:1: error: conflicting types for 'i2d_CVC_CERT'
IMPLEMENT_ASN1_FUNCTIONS(CVC_CERT)
```

**Comment by frankmorgner** [comment]
which version of macOS are you using? do you have some local installation of OpenSSL or some other version of OpenPACE?

**Comment by frankmorgner** [comment]
The compiler flags for macOS are not trivial. I've included a script in the Makefile to do that. Please try
```
./configure
make osx
```
If that doesn't work out of the box (anymore), please adapt the single steps to your need:
https://github.com/frankmorgner/openpace/blob/e92496e932a4c51b41a89dd1642c92f7795cc76e/cross/Makefile.am#L10-L31

**Comment by ryandesign** [comment]
I can confirm the reported problem using openssl 3.0.1 in MacPorts. It builds fine with using openssl 1.1.1. I'll modify the MacPorts openpace port to do this.

**Comment by frankmorgner** [comment]
I can't confirm this with OpenSSL 3.0 on Linux. What exactly is needed to reproduce this on macOS?
